version: '3.4'

services:
  heinekamp-api:
    build:
      context: .
      dockerfile: ./Presentation/Heinekamp.Api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - FrontEndApplication=http://localhost:3000
    networks:
      - heinekamp

  frontend-app:
    build:
      context: .
      dockerfile: ./front-end/heinekamp-app/Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
    networks:
      - heinekamp

networks:
  heinekamp:
    driver: bridge